# Generated by Django 4.1.7 on 2023-08-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_title', models.CharField(max_length=50)),
                ('banner_img', models.ImageField(upload_to='myapp/images/banner')),
                ('banner_desc', models.CharField(max_length=100)),
                ('banner_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
