# Generated by Django 4.1.7 on 2023-08-20 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lodge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=250)),
                ('mob', models.BigIntegerField()),
                ('fees', models.IntegerField()),
            ],
        ),
    ]
