# Generated by Django 4.1.7 on 2023-08-20 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_lodge'),
    ]

    operations = [
        migrations.AddField(
            model_name='lodge',
            name='img',
            field=models.ImageField(default=None, upload_to='myapp/images/lodge'),
        ),
    ]
