# Generated by Django 4.1.7 on 2023-07-31 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuid', models.IntegerField()),
                ('stuname', models.CharField(max_length=45)),
                ('stuemail', models.EmailField(max_length=70)),
                ('stun', models.CharField(max_length=68)),
            ],
        ),
    ]
